[project]
name = "paymaster-cache"
authors = ["Web3 Infrastructure Team"]
description = "Decentralized transaction gas estimation caching system for cross-chain paymaster operations"
telemetry = false
requirements = []
[contracts.cache-manager]
path = "contracts/cache-manager.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = true
trusted_sender = false
trusted_caller = false
callee_filter = false
